name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use ubuntu-latest for Linux builds

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    - name: Create directories
      run: |
        mkdir -p cpp/obj cpp/bin

    - name: Build project
      run: |
        make -C cpp all || { echo 'Build failed'; exit 1; }

    - name: List files
      run: |
        echo "Listing files in the build directory:"
        ls -R cpp/bin

    - name: Run tests
      run: |
        # Add commands to run tests if applicable
        # For example: ./cpp/bin/app --test
        echo "No tests to run"

    - name: Clean up
      run: |
        make -C cpp clean || { echo 'Clean up failed'; exit 1; }
