name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 python-is-python3 libgtest-dev

      - name: Run config64.py
        run: |
          cd cpp/Lib
          echo -e "1\n0" | python config64.py

      - name: Build project
        run: |
          cd cpp && make CXXFLAGS="-fsanitize=address -fno-omit-frame-pointer -g"

      - name: Run application
        run: |
          cd cpp && ASAN_OPTIONS=detect_leaks=1 ./bin/app
