name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ environment
      uses: actions/setup-cpp@v2
      with:
        compiler: 'gcc' # Use 'clang' if you prefer Clang

    - name: Install build dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build project
      run: cmake --build build

    - name: Run tests
      run: |
        cd build
        make test || true  # Replace with your actual test command if different

    - name: Package the project
      run: |
        cd build
        make package || true  # Replace with your actual packaging command if different
